spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/Sports
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.security: INFO
    com.sports.backend: DEBUG
